name: Main Workflow

on:
  push:
    branches:
      - main  # Se ejecuta en la rama 'main'
  pull_request:
    branches:
      - main

jobs:
  backend-setup-and-tests:
    name: Backend Setup and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install backend dependencies
        run: |
          cd src/backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Alembic migrations
        run: |
          cd src/backend
          source venv/bin/activate
          alembic upgrade head

      - name: Run backend tests
        run: |
          cd src/backend
          source venv/bin/activate
          python -m pytest

  frontend-setup-and-deploy:
    name: Frontend Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install frontend dependencies
        run: |
          cd src/filmHub
          npm install

      - name: Run frontend build
        run: |
          cd src/filmHub
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/filmHub/dist
