name: Run Integration Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set USE_SELE_CONFIG=false and apply database migrations (backend)
        working-directory: src/backend
        run: |
          export USE_SELE_CONFIG=false
          alembic upgrade head

      - name: Set USE_SELE_CONFIG=false and start the server (filmhub)
        working-directory: src/filmHub
        run: |
          export USE_SELE_CONFIG=false
          npm install  # Ensure all npm dependencies are installed
          npm run serve &

          # Wait for the server to be ready using curl
          until curl -s http://localhost:8080/login; do
            echo "Waiting for backend to be ready..."
            sleep 5
          done

      - name: Install Chrome and dependencies for Selenium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser
          sudo apt install -y chromium-chromedriver
          sudo apt install -y libnss3 libgconf-2-4

      - name: Run tests
        working-directory: src/backend
        run: pytest app/tests/integration
