name: Run Integration Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set USE_SELE_CONFIG=false and apply database migrations (backend)
        working-directory: src/backend
        run: |
          export USE_SELE_CONFIG=false
          alembic upgrade head

      - name: Install Vue CLI globally
        run: |
          cd src
          npm install -g @vue/cli

      - name: Install frontend dependencies and run the server (filmHub)
        working-directory: src/filmHub
        run: |
          # Install frontend dependencies
          npm install
          npm install axios
          npm install flatpickr
          # Start the Vue.js development server
          export USE_SELE_CONFIG=false
          nohup npm run serve &

          # Wait for the frontend server to be available
          for url in "http://localhost:8080/login" "http://localhost:8080/register" "http://localhost:8080/movie/2" "http://localhost:8080/movie/3" "http://localhost:8080/movie/4" "http://localhost:8080/movie/5"; do
            until curl -s "$url" > /dev/null; do
              echo "Waiting for $url to be ready..."
              sleep 5
            done
          done

      - name: Install Chrome and dependencies for Selenium
        run: |
          sudo apt update
          sudo apt install -y chromium-browser
          sudo apt install -y chromium-chromedriver
          sudo apt install -y libnss3 libgconf-2-4

      - name: Set up Chrome environment variables for Selenium
        run: |
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PATH=/usr/lib/chromium-browser/chromedriver" >> $GITHUB_ENV

      - name: Run tests
        working-directory: src/backend
        run: pytest app/tests/integration 
