name: Run Unit Tests

on:
  push:            # Trigger the workflow on push
  pull_request:    # Trigger the workflow on pull requests

jobs:
  test:
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'   # Adjust the Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Apply database migrations
        working-directory: src/backend
        run: alembic upgrade head

      - name: Run tests with coverage
        working-directory: src/backend
        run: |
          pytest --cov=app/crud --cov-report=xml --cov-report=term-missing app/crud/tests

      - name: Upload coverage report (optional)
        if: success()  # Only upload if tests pass
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: src/backend/coverage.xml
